#!/bin/bash

# Delay 30 seconds to wait entity manager fully populate the system configs.
# Needs to enhance this in future.
sleep 30

INVENTORY_OUTPUT="$(mfg-tool inventory 2>/dev/null)"

HDD_HW_REV="$(echo "${INVENTORY_OUTPUT}" | jq -r '."system/board/Catalina_HDD_Carrier"."Decorator.Revision"."Version"')"
SCM_HW_REV="$(echo "${INVENTORY_OUTPUT}" | jq -r '."system/board/Catalina_SCM"."Decorator.Revision"."Version"')"
PDB_HW_REV="$(echo "${INVENTORY_OUTPUT}" | jq -r '."system/board/Catalina_PDB"."Decorator.Revision"."Version"')"
PDB_VR_TYPE="raa"

# If 19-0063 exist, Delta brick is uesd on this PDB board
if [ "$(i2cdetect -y -q 19 0x63 0x63 | awk '/60:/ {print $2}')" != "--" ]; then
    PDB_VR_TYPE="delta"
fi

kv set hdd_hw_rev "${HDD_HW_REV}"
kv set scm_hw_rev "${SCM_HW_REV}"
kv set pdb_hw_rev "${PDB_HW_REV}"
kv set pdb_vr_type "${PDB_VR_TYPE}"
