mux-gpios = SLOT5_UART_SEL0,SLOT5_UART_SEL1,SLOT5_UART_SEL2
baud = 57600
console-id = host5
logsize = 256k

[wf_bic5]
mux-index = 1
logfile = /var/log/obmc-console-wf-bic5.log

[host5]
mux-index = 3
logfile = /var/log/obmc-console-host5.log

[sd_bic5]
mux-index = 4
logfile = /var/log/obmc-console-sd-bic5.log
