mux-gpios = SLOT2_UART_SEL0,SLOT2_UART_SEL1,SLOT2_UART_SEL2
baud = 57600
console-id = host2
logsize = 256k

[wf_bic2]
mux-index = 1
logfile = /var/log/obmc-console-wf-bic2.log

[host2]
mux-index = 3
logfile = /var/log/obmc-console-host2.log

[sd_bic2]
mux-index = 4
logfile = /var/log/obmc-console-sd-bic2.log
