mux-gpios = SLOT3_UART_SEL0,SLOT3_UART_SEL1,SLOT3_UART_SEL2
baud = 57600
console-id = host3
logsize = 256k

[wf_bic3]
mux-index = 1
logfile = /var/log/obmc-console-wf-bic3.log

[host3]
mux-index = 3
logfile = /var/log/obmc-console-host3.log

[sd_bic3]
mux-index = 4
logfile = /var/log/obmc-console-sd-bic3.log
