mux-gpios = SLOT6_UART_SEL0,SLOT6_UART_SEL1,SLOT6_UART_SEL2
baud = 57600
console-id = host6
logsize = 256k

[wf_bic6]
mux-index = 1
logfile = /var/log/obmc-console-wf-bic6.log

[host6]
mux-index = 3
logfile = /var/log/obmc-console-host6.log

[sd_bic6]
mux-index = 4
logfile = /var/log/obmc-console-sd-bic6.log
