#include "http_client.hpp"

#include <boost/asio.hpp>
#include <boost/bind/bind.hpp>
#include <boost/system/error_code.hpp>

#include <atomic>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>

#include <gtest/gtest.h>

namespace
{

class SimpleTestHttpServer
{
  public:
    struct ReceivedHttpRequest
    {
        std::string method;
        std::string path;
        std::string version;
        std::unordered_map<std::string, std::string> headers;
    };

    explicit SimpleTestHttpServer(
        const std::string& responseStr,
        const std::unordered_map<std::string, std::string>& responseHeaders) :
        responseStr(responseStr), responseHeaders(responseHeaders),
        // Start on port 0 to let the OS pick an available port.
        acceptor(ioContext,
                 boost::asio::ip::tcp::endpoint(boost::asio::ip::tcp::v4(), 0)),
        port(acceptor.local_endpoint().port())
    {
        startAccept();
        serverThread = std::make_unique<std::thread>([this]() {
            ioContext.run();
            serverThreadStopped = true;
        });
    }

    ~SimpleTestHttpServer()
    {
        if (!serverThreadStopped)
        {
            stopListening();
        }
    }

    SimpleTestHttpServer(const SimpleTestHttpServer&) = delete;
    SimpleTestHttpServer(SimpleTestHttpServer&&) = delete;
    SimpleTestHttpServer& operator=(const SimpleTestHttpServer&) = delete;
    SimpleTestHttpServer& operator=(SimpleTestHttpServer&&) = delete;

    void stopListening()
    {
        acceptor.cancel();
        serverThread->join();
    }

    unsigned short getPort()
    {
        return port;
    }

    std::vector<ReceivedHttpRequest> getReceivedRequests()
    {
        std::lock_guard<std::mutex> lock(requestsMutex);
        return requests;
    }

  private:
    //  Very simple HTTP request parsing logic that only works for the requests
    //  generated by this test.
    static ReceivedHttpRequest parseSimpleRequest(const std::string& requestStr)
    {
        ReceivedHttpRequest rv;

        // Parse the first line (method, url, version)
        size_t pos = requestStr.find(' ');
        rv.method = requestStr.substr(0, pos);
        size_t pos2 = requestStr.find(' ', pos + 1);
        rv.path = requestStr.substr(pos + 1, pos2 - pos - 1);
        rv.version =
            requestStr.substr(pos2 + 1, requestStr.find('\n') - pos2 - 1);

        // Parse the headers
        while ((pos = requestStr.find('\n', pos2)) != std::string::npos)
        {
            pos2 = requestStr.find('\n', pos + 1);
            if (pos2 == std::string::npos)
                break;
            size_t colonPos = requestStr.find(':', pos + 1);
            if (colonPos == std::string::npos || colonPos > pos2)
                continue;
            std::string key = requestStr.substr(pos + 1, colonPos - pos - 1);
            std::string value =
                requestStr.substr(colonPos + 1, pos2 - colonPos - 1);
            rv.headers[key] = value;
        }
        return rv;
    }

    void handleAccept(const boost::system::error_code& error,
                      std::shared_ptr<boost::asio::ip::tcp::socket> socket)
    {
        if (error)
        {
            // Server stopping, no need to process this request.
            return;
        }
        boost::asio::streambuf requestBuffer;
        boost::asio::read_until(*socket, requestBuffer, "\r\n\r\n");

        std::string requestStr((std::istreambuf_iterator<char>(&requestBuffer)),
                               std::istreambuf_iterator<char>());
        ReceivedHttpRequest request = parseSimpleRequest(requestStr);

        // Response result.
        std::string response = "HTTP/1.1 200 OK\r\n";

        // Add some response headers.
        for (const auto& header : responseHeaders)
        {
            response += header.first + ": " + header.second + "\r\n";
        }

        // Response body.
        response += "\r\n";
        response += responseStr;
        boost::asio::write(*socket, boost::asio::buffer(response));
        updateReceivedRequest(request);
        startAccept();
    }

    void updateReceivedRequest(const ReceivedHttpRequest& request)
    {
        std::lock_guard<std::mutex> lock(requestsMutex);
        requests.push_back(request);
    }

    void startAccept()
    {
        auto socket = std::make_shared<boost::asio::ip::tcp::socket>(ioContext);
        acceptor.async_accept(
            *socket, boost::bind(&SimpleTestHttpServer::handleAccept, this,
                                 boost::asio::placeholders::error, socket));
    }

    std::string responseStr;
    std::unordered_map<std::string, std::string> responseHeaders;
    std::vector<ReceivedHttpRequest> requests;
    std::mutex requestsMutex;
    boost::asio::io_context ioContext;
    boost::asio::ip::tcp::acceptor acceptor;
    unsigned short port;
    std::unique_ptr<std::thread> serverThread;
    std::atomic<bool> serverThreadStopped{false};
};

} // namespace

TEST(HttpClientTests, TestClient)
{
    redfish_client_daemon::HttpClient::globalInit();
    auto client = std::make_unique<redfish_client_daemon::HttpClient>(1);

    static constexpr int kIters = 10;
    std::string responseBody = "Hello, World!";
    std::unordered_map<std::string, std::string> responseHeaders;
    responseHeaders["h0"] = "v0";
    responseHeaders["h1"] = "v1";
    responseHeaders["h2"] = "v2";
    SimpleTestHttpServer server(responseBody, responseHeaders);
    unsigned short port = server.getPort();
    std::string url = "http://localhost:" + std::to_string(port) + "/";

    // Run it a few times to detect flakiness with higher probability.
    for (int j = 0; j < kIters; ++j)
    {
        // Test the response received by the client.
        auto response = client->get(url.c_str());
        EXPECT_EQ(200, response.responseCode);
        EXPECT_EQ(3, response.headers.size());
        EXPECT_STREQ("v0", response.headers["h0"].c_str());
        EXPECT_STREQ("v1", response.headers["h1"].c_str());
        EXPECT_STREQ("v2", response.headers["h2"].c_str());

        response.body.push_back(0);
        const char* bodyCstr = response.body.data();
        EXPECT_STREQ(responseBody.c_str(), bodyCstr);
    }
    server.stopListening();
    auto requestsCopy = server.getReceivedRequests();
    for (const auto& request : requestsCopy)
    {
        // Make a local copy of the headers so that we can drop the
        // const for verification.
        auto headers = request.headers;
        EXPECT_STREQ("GET", request.method.c_str());
        EXPECT_STREQ("/", request.path.c_str());
        EXPECT_TRUE(strstr(request.version.c_str(), "HTTP/1.1") != nullptr);
        EXPECT_TRUE(strstr(headers["Accept"].c_str(), "*/*") != nullptr);
        EXPECT_TRUE(strstr(headers["User-Agent"].c_str(), "curl") != nullptr);
    }

    // Destroy the client before global deinit.
    client = nullptr;
    redfish_client_daemon::HttpClient::globalDeinit();
}
