# HPDB main source
chip "adm1272-i2c-39-1c"
    label in1    "HSC1_VIN_VOLT"
    label in2    "HSC1_VOUT_VOLT"
    label curr1  "HSC1_CURR"
    label power1 "HSC1_PWR"
    label temp1  "HSC1_TEMP"
    compute curr1 @/0.15*0.9465 + 0.3856, @*0.15
    compute power1 @/0.15*0.9535 + 4.4113, @*0.15

chip "adm1272-i2c-39-13"
    label in1    "HSC2_VIN_VOLT"
    label in2    "HSC2_VOUT_VOLT"
    label curr1  "HSC2_CURR"
    label power1 "HSC2_PWR"
    label temp1  "HSC2_TEMP"
    compute curr1 @/0.15*0.9445 + 0.1574, @*0.15
    compute power1 @/0.15*0.9488 + 16.9462, @*0.15

chip "adm1272-i2c-39-10"
    label in1    "HSC3_VIN_VOLT"
    label in2    "HSC3_VOUT_VOLT"
    label curr1  "HSC3_CURR"
    label power1 "HSC3_PWR"
    label temp1  "HSC3_TEMP"
    compute curr1 @/0.25*0.98-0.19, @*0.25
    compute power1 @/0.25*0.98 - 12.85, @*0.25

chip "adm1272-i2c-39-1f"
    label in1    "HSC4_VIN_VOLT"
    label in2    "HSC4_VOUT_VOLT"
    label curr1  "HSC4_CURR"
    label power1 "HSC4_PWR"
    label temp1  "HSC4_TEMP"
    compute curr1 @/0.25*0.98-0.02, @*0.25
    compute power1 @/0.25*0.98 - 4.29, @*0.25

# HPDB second source
chip "ltc4286-i2c-39-40"
    label in1    "HSC1_VIN_VOLT"
    label in2    "HSC1_VOUT_VOLT"
    label curr1  "HSC1_CURR"
    label power1 "HSC1_PWR"
    label temp1  "HSC1_TEMP"
    compute curr1 (@/0.1)*0.94+0.73, @*0.1
    compute power1 (@/0.1)*0.94+39.36, @*0.1

chip "ltc4286-i2c-39-41"
    label in1    "HSC2_VIN_VOLT"
    label in2    "HSC2_VOUT_VOLT"
    label curr1  "HSC2_CURR"
    label power1 "HSC2_PWR"
    label temp1  "HSC2_TEMP"
    compute curr1 (@/0.1)*0.94+1, @*0.1
    compute power1 (@/0.1)*0.94+53.14, @*0.1

chip "ltc4286-i2c-39-42"
    label in1    "HSC3_VIN_VOLT"
    label in2    "HSC3_VOUT_VOLT"
    label curr1  "HSC3_CURR"
    label power1 "HSC3_PWR"
    label temp1  "HSC3_TEMP"
    compute curr1 (@/0.15)*0.94-0.07, @*0.15
    compute power1 (@/0.15)*0.94-4.13, @*0.15

chip "ltc4286-i2c-39-46"
    label in1    "HSC4_VIN_VOLT"
    label in2    "HSC4_VOUT_VOLT"
    label curr1  "HSC4_CURR"
    label power1 "HSC4_PWR"
    label temp1  "HSC4_TEMP"
    compute curr1 (@/0.15)*0.94-0.11, @*0.15
    compute power1 (@/0.15)*0.94-6.73, @*0.15
