# HPDB main source
chip "adm1272-i2c-39-1c"
    label in1    "HSC1_VIN_VOLT"
    label in2    "HSC1_VOUT_VOLT"
    label curr1  "HSC1_CURR"
    label power1 "HSC1_PWR"
    label temp1  "HSC1_TEMP"
    compute curr1 @/0.1*0.94+0.05, @*0.1
    compute power1 @/0.1*0.95-8.96, @*0.1

chip "adm1272-i2c-39-13"
    label in1    "HSC2_VIN_VOLT"
    label in2    "HSC2_VOUT_VOLT"
    label curr1  "HSC2_CURR"
    label power1 "HSC2_PWR"
    label temp1  "HSC2_TEMP"
    compute curr1 @/0.1*0.94+0.23, @*0.1
    compute power1 @/0.1*0.94+9.82, @*0.1

chip "adm1272-i2c-39-10"
    label in1    "HSC3_VIN_VOLT"
    label in2    "HSC3_VOUT_VOLT"
    label curr1  "HSC3_CURR"
    label power1 "HSC3_PWR"
    label temp1  "HSC3_TEMP"
    compute curr1 @/0.25*0.992+0.0912, @*0.25
    compute power1 @/0.25*0.995+1.9427, @*0.25

chip "adm1272-i2c-39-1f"
    label in1    "HSC4_VIN_VOLT"
    label in2    "HSC4_VOUT_VOLT"
    label curr1  "HSC4_CURR"
    label power1 "HSC4_PWR"
    label temp1  "HSC4_TEMP"
    compute curr1 @/0.25*0.9878+0.02144, @*0.25
    compute power1 @/0.25*0.9904+1.6601, @*0.25

# HPDB second source
chip "ltc4286-i2c-39-40"
    label in1    "HSC1_VIN_VOLT"
    label in2    "HSC1_VOUT_VOLT"
    label curr1  "HSC1_CURR"
    label power1 "HSC1_PWR"
    label temp1  "HSC1_TEMP"
    compute curr1 (@/0.1)*0.9547-0.0616, @*0.1
    compute power1 (@/0.1)*0.9519-3.8684, @*0.1

chip "ltc4286-i2c-39-41"
    label in1    "HSC2_VIN_VOLT"
    label in2    "HSC2_VOUT_VOLT"
    label curr1  "HSC2_CURR"
    label power1 "HSC2_PWR"
    label temp1  "HSC2_TEMP"
    compute curr1 (@/0.1)*0.9536-0.0736, @*0.1
    compute power1 (@/0.1)*0.9518-4.7627, @*0.1

chip "ltc4286-i2c-39-42"
    label in1    "HSC3_VIN_VOLT"
    label in2    "HSC3_VOUT_VOLT"
    label curr1  "HSC3_CURR"
    label power1 "HSC3_PWR"
    label temp1  "HSC3_TEMP"
    compute curr1 (@/0.15)*0.9565+0.0068, @*0.15
    compute power1 (@/0.15)*0.9538+0.2586, @*0.15

chip "ltc4286-i2c-39-46"
    label in1    "HSC4_VIN_VOLT"
    label in2    "HSC4_VOUT_VOLT"
    label curr1  "HSC4_CURR"
    label power1 "HSC4_PWR"
    label temp1  "HSC4_TEMP"
    compute curr1 (@/0.15)*0.96+0.0009, @*0.15
    compute power1 (@/0.15)*0.9569-0.0032, @*0.15
