#!/bin/bash
set -e

max_retry_count=10
retry_delay_sec=3

version=""
for ((i=1; i<=max_retry_count; i++)); do
    version=$(fw-util cb --version cb_cpld | sed -n 's/.*: //p')
    if [ -z "$version" ] || [[ "$version" == *"NA"* ]]; then
        echo "failed to get version, version=${version}, retry after ${retry_delay_sec} seconds (count: ${i})"
        sleep "$retry_delay_sec"
    else
        break
    fi
done

echo "CB CPLD version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Minerva_CB_cb_cpld \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
